# Generated by Django 6.0.1 on 2026-01-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('new_price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('category', models.CharField(choices=[('living room', 'Living Room'), ('bedroom', 'Bedroom'), ('dining room', 'Dining Room'), ('lamps & lighting', 'Lamps & Lighting')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
